RAW_PATH = "../data/raw/CC GENERAL.csv"
PROCESSED_DIR = "../data/processed"
RANDOM_STATE = 42

ID_COL = "CUST_ID"
IMPUTE_MEDIAN_COLS = ["MINIMUM_PAYMENTS"]

LOG1P_COLS = [
    "BALANCE","PURCHASES","ONEOFF_PURCHASES","INSTALLMENTS_PURCHASES",
    "CASH_ADVANCE","PAYMENTS","MINIMUM_PAYMENTS","CREDIT_LIMIT"
]

RISK_COLS = ["PAYMENTS","MINIMUM_PAYMENTS","PRC_FULL_PAYMENT","BALANCE"]
CREDIT_BEHAVIOR_COLS = ["CREDIT_LIMIT","BALANCE","CASH_ADVANCE","CASH_ADVANCE_FREQUENCY","CASH_ADVANCE_TRX"]
CONSUMPTION_COLS = ["PURCHASES","ONEOFF_PURCHASES","INSTALLMENTS_PURCHASES","PURCHASES_FREQUENCY",
                    "ONEOFF_PURCHASES_FREQUENCY","PURCHASES_INSTALLMENTS_FREQUENCY","PURCHASES_TRX"]
